# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: \.svg$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language: python
-   repo: local
    hooks:
    -   id: prettier
        name: prettier
        entry: bash -c "cd web_new && yarn prettier --write ."
        language: node
    -   id: eslint
        name: eslint
        entry: bash -c "cd web_new && yarn next lint --fix"
        language: node
# The hook below is just used for debugging when necessary.
# The example below checks if a hook is indeed applied to the specified files.
# See https://pre-commit.com/#meta-hooks for more details.
# -   repo: meta
#     hooks:
#     -   id: identity
#         name: identity (filtered)
#         files: ^web_new\/.*(\.[jt]sx?$)  # *.js, *.jsx, *.ts and *.tsx in web_new folder
