# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: \.svg$
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language: python
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
    -   id: prettier
        files: ^web_new
        args: [--ignore-path=web_new/.prettierignore]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.33.0
    hooks:
    -   id: eslint
        files: ^web_new/.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
        -   eslint-config-next@13.1.6
        -   eslint-config-prettier@8.6.0
