version: "3"

services:
  api:
    build:
      dockerfile: ./server.Dockerfile
    restart: always
    entrypoint: ["nohup", "uvicorn", "server.main:app", "--reload", "--host", "0.0.0.0"]  
    ports:
      - "6456:8000"
  web:
    build:
      dockerfile: ./web.Dockerfile
    restart: always
    entrypoint: ["yarn","start"]
    ports:
      - "6455:3000"
    depends_on:
      - api
