version: "3"

services:
  fast:
    build:
      dockerfile: ../server.Dockerfile
      context: server
    restart: always
    entrypoint: ["nohup", "uvicorn", "server.main:app", "--reload", "--host", "0.0.0.0"]  
    ports:
      - "6456:8000"
  best:
    build:
      dockerfile: ../server.Dockerfile
      context: server
    restart: always
    entrypoint: ["nohup", "uvicorn", "server.main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"] 
    volumes:
      - ./models/best/checkpoint_best.pt:/app/server/models/checkpoint_best.pt
      - ./models/best/bin:/app/server/binary
    ports:
      - "6457:8001"
  web:
    build:
      dockerfile: ../web.Dockerfile
      context: web
    restart: always
    entrypoint: ["yarn","start"]
    ports:
      - "6455:3000"
    depends_on:
      - fast
      - best
