name: "Tests CI"

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  cli-pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Set up environment
        run: pip install -r requirements.txt
      - name: Test with pytest
        run: pytest -vv

  web-jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --immutable --immutable-cache --check-cache
          dir: "web_new"
      - name: Run tests
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: "web_new"
